name: setup
runs:
  using: "composite"
  steps:
    - name: set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash