name: setup
runs:
  using: "composite"
  steps:
    - name: set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Create file
      run: touch /home/runner/work/httpcodescats/httpcodescats/app/src/google-services.json
      shell: bash
    - name: Create Google Services JSON File
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 -di > /home/runner/work/httpcodescats/httpcodescats/app/src/google-services.json
      shell: bash

