name: build

runs:
  using: "composite"
  steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HttpCodesCats
        path: |
          ./app/build/outputs/**/*.apk
          ./app/build/outputs/**/*signed.aab
